#! /bin/sh

### BEGIN INIT INFO
# Provides:    biotraq
# Required-Start: $remote_fs $syslog
# Required-Stop:  $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: BioTraq
### END INIT INFO

## BioTraq settings

VERSION="1.0.0"
INSTALL_DIR="/home/youruser/biotraq"
CONFIG="biotraq.conf"
OPTS=""

## Linux user and group for BioTraq process
RUN_AS_USER="biotraq"
RUN_AS_GROUP="biotraq"

## memory settings for the JVM
MIN_MEMORY="256M"
MAX_MEMORY="512M"


PID_FILE="/var/run/biotraq.pid"

## do not change the following

JAR="$INSTALL_DIR/biotraq-$VERSION.jar"

JAVA=`(command -v java)`
JAVA_BIOTRAQ_OPTS="-Xms$MIN_MEMORY -Xmx$MAX_MEMORY -jar $JAR run -c $CONFIG $OPTS"


PID_FILE="/var/run/biotraq.pid"


# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting BioTraq" "biotraq" || true
    if start-stop-daemon --start --oknodo --quiet --chuid "$RUN_AS_USER:$RUN_AS_GROUP" --chdir $INSTALL_DIR --background --make-pidfile --pidfile $PID_FILE --exec $JAVA -- $JAVA_BIOTRAQ_OPTS; then
       log_end_msg 0 || true
    else
       log_end_msg 1 || true
    fi
    ;;
  stop)
    log_daemon_msg "Stopping BioTraq" "biotraq" || true
    if start-stop-daemon --stop --oknodo --quiet --pidfile $PID_FILE; then
       log_end_msg 0 || true
    else
       log_end_msg 1 || true
    fi
    ;;
  restart)
   log_daemon_msg "Restarting BioTraq" "biotraq" || true
   start-stop-daemon --stop --oknodo --quiet --retry 30 --pidfile $PID_FILE
   if start-stop-daemon --start --oknodo --quiet --chuid "$RUN_AS_USER:$RUN_AS_GROUP" --chdir $INSTALL_DIR --background --make-pidfile --pidfile $PID_FILE --exec $JAVA -- $JAVA_BIOTRAQ_OPTS; then
       log_end_msg 0 || true
   else
       log_end_msg 1 || true
   fi
   ;;
  *)
    log_action_msg "Usage: /etc/init.d/biotraq {start|stop|restart}" || true
    exit 1
esac

exit 0
